In [120]:
import numpy as np
import pandas as pd

In [122]:
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

In [123]:
np_zp = np.array(zp)
np_ks = np.array(ks)


In [124]:
print(np_zp * np_ks)

[ 14035  25830 166060 183800  18360  51730  35262 135300  89520  91520]


In [125]:
my_cov = np.mean(np_zp * np_ks) - np.mean(np_zp) * np.mean(np_ks)
my_cov

9157.839999999997

In [126]:
cov_np = np.cov(np_ks, np_zp, ddof = 0)
cov_np

array([[30468.89,  9157.84],
       [ 9157.84,  3494.64]])

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [127]:
sig_np_ks = np.std(np_ks)
sig_np_ks

174.55340157098058

In [128]:
sig_np_zp = np.std(np_zp)
sig_np_zp

59.115480206118605

In [129]:
my_pirson = cov_np[0][1] / (sig_np_ks * sig_np_zp)
my_pirson

0.8874900920739162

In [130]:
corr = np.corrcoef(np_ks, np_zp)
corr

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [131]:
def list_for_df(arr_1, arr_2):
    new_arr = []
    sum_arr = []
    for i in range(len(arr_1)):
        new_arr = []
        new_arr.append(arr_1[i])
        new_arr.append(arr_2[i])
        sum_arr.append(new_arr)
    return sum_arr


In [132]:
for_df = list_for_df(zp, ks)
for_df

[[35, 401],
 [45, 574],
 [190, 874],
 [200, 919],
 [40, 459],
 [70, 739],
 [54, 653],
 [150, 902],
 [120, 746],
 [110, 832]]

In [133]:
df = pd.DataFrame(for_df, columns=['zp', 'ks'])
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [138]:
df.corr(method = 'pearson')

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

2) Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [139]:
np_arr = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
np_arr

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [140]:
mean_iq = np.mean(np_arr)
mean_iq


118.1

In [141]:
sigma = np.std(np_arr, ddof = 1)
sigma

10.54566788359614

In [142]:
z = 1.96

In [143]:
int = [mean_iq + (1.96 * sigma / (len(np_arr) ** 1/2) ), mean_iq - (1.96 * sigma / (len(np_arr) ** 1/2) )]
int

[122.23390181036969, 113.9660981896303]

3) Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [145]:
mean_height = 174.2
sigma = 5
count = 27

In [147]:
int = [mean_height + (1.96 * (sigma / (count * 1/2)) ), mean_height - (1.96 * (sigma / (count ** 1/2)) )]
int

[174.92592592592592, 173.47407407407405]